//
//  TableView+Extensions.swift
//  TVShow
//
//  Created by Chu Anh Minh on 5/27/19.
//  Copyright © 2019 MinhChu. All rights reserved.
//

import UIKit

public extension UIView {
    static var autoReuseIdentifier: String {
        return NSStringFromClass(self) + "AutogeneratedIdentifier"
    }
}

public extension UITableView {
    func dequeue<T: UITableViewCell>(for indexPath: IndexPath) -> T {
        guard let cell = dequeueReusableCell(withIdentifier: T.autoReuseIdentifier, for: indexPath) as? T else {
            fatalError("Unknown cell")
        }
        return cell
    }

    func dequeueHeaderFooterView<T: UIView>() -> T {
        guard let view = dequeueReusableHeaderFooterView(withIdentifier: T.autoReuseIdentifier) as? T else {
            fatalError()
        }
        return view
    }

    func registerCell<T: UITableViewCell>(_ cell: T.Type) {
        register(nibFromClass(cell), forCellReuseIdentifier: cell.autoReuseIdentifier)
    }

    func registerSectionHeaderFooter<T: UIView>(_ view: T.Type) {
        register(nibFromClass(view), forHeaderFooterViewReuseIdentifier: view.autoReuseIdentifier)
    }

    // Private

    fileprivate func nibFromClass(_ type: UIView.Type) -> UINib? {
        guard let nibName = NSStringFromClass(type).components(separatedBy: ".").last
            else {
                return nil
        }

        return UINib(nibName: nibName, bundle: nil)
    }
}

public extension UICollectionView {
    var currentPageNumber: Int {
        return Int(ceil(self.contentOffset.x / self.frame.size.width))
    }

    func dequeue<T: UICollectionViewCell>(for indexPath: IndexPath) -> T {
        guard let cell = dequeueReusableCell(withReuseIdentifier: T.autoReuseIdentifier, for: indexPath) as? T else {
            fatalError("WTF man?")
        }
        return cell
    }
    func dequeue<T: UICollectionReusableView>(header: T.Type, indexPath: IndexPath) -> T? {
        return  dequeueReusableSupplementaryView(
            ofKind: UICollectionView.elementKindSectionHeader,
            withReuseIdentifier: header.autoReuseIdentifier,
            for: indexPath)    as? T
    }

    func dequeue<T: UICollectionReusableView>(footer: T.Type, indexPath: IndexPath) -> T? {
        return  dequeueReusableSupplementaryView(
            ofKind: UICollectionView.elementKindSectionFooter,
            withReuseIdentifier: footer.autoReuseIdentifier,
            for: indexPath)    as? T
    }

    func registerCell<T: UICollectionReusableView>(_ cell: T.Type) {
        register(nibFromClass(cell), forCellWithReuseIdentifier: cell.autoReuseIdentifier)
    }

    func registerSectionHeader<T: UICollectionReusableView>(_ header: T.Type) {
        register(nibFromClass(header), forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader,
                 withReuseIdentifier: header.autoReuseIdentifier)
    }

    func registerSectionFooter<T: UICollectionReusableView>(_ footer: T.Type) {
        register(nibFromClass(footer), forSupplementaryViewOfKind: UICollectionView.elementKindSectionFooter,
                 withReuseIdentifier: footer.autoReuseIdentifier)
    }

    // Private

    private func nibFromClass(_ type: UICollectionReusableView.Type) -> UINib? {
        guard let nibName = NSStringFromClass(type).components(separatedBy: ".").last
            else {
                return nil
        }

        return UINib(nibName: nibName, bundle: nil)
    }
}
